name: control_point_2
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  lints: ^2.0.0
  test: ^1.21.0
